#!name=LimbusCompany IOS Localization
#!desc=边狱巴士ios汉化模块 by ghcruise

[URL Rewrite]
^https?://.*localize_jp.zip$ https://raw.githubusercontent.com/admin05/LimbusCompany-IOS-Localization/refs/heads/main/localize_jp.zip 302

^https://downloadcommon\.limbuscompanycdn\.org/.*LocalizePatchInfo\.json$ https://raw.githubusercontent.com/admin05/LimbusCompany-IOS-Localization/refs/heads/main/manifest.json 302

[MITM]
hostname = *.limbuscompanycdn.org
